/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileSizeTree.java
 *
 * Created on 07.11.2009, 22:35:13
 */
package com.kenai.paranoidray.fst;

import java.awt.Dimension;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Ray
 */
public class FileSizeTree extends javax.swing.JFrame {
    final JFreeChart chart;
    final DefaultPieDataset dataset;

    /** Creates new form FileSizeTree */
    public FileSizeTree() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTreeCellRenderer dtcr = (DefaultTreeCellRenderer) fileSizeTree.getCellRenderer();
        dtcr.setLeafIcon(dtcr.getClosedIcon());

        DefaultTreeCellRenderer renderer = new DefaultTreeCellRenderer();
        renderer.setLeafIcon(renderer.getClosedIcon());
        fileSizeTree.setCellRenderer(renderer);

        dataset = FSTUtil.createSampleDataset();

        // create the chart...
        chart = FSTUtil.createChart(dataset);

        // add the chart to a panel...
        final ChartPanel chartPanel = new ChartPanel(chart);
        //chartPanel.setPreferredSize(new java.awt.Dimension(500, 270));

        jPanel1.add(chartPanel);
        this.pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneForTree = new javax.swing.JScrollPane();
        fileSizeTree = new javax.swing.JTree();
        jPanelTop = new javax.swing.JPanel();
        jTextFieldPath = new javax.swing.JTextField();
        jButtonSelectPath = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FileSizeTree");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        fileSizeTree.setModel(null);
        fileSizeTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                fileSizeTreeValueChanged(evt);
            }
        });
        jScrollPaneForTree.setViewportView(fileSizeTree);

        getContentPane().add(jScrollPaneForTree, java.awt.BorderLayout.CENTER);

        jPanelTop.setPreferredSize(new java.awt.Dimension(578, 30));
        jPanelTop.setLayout(new java.awt.BorderLayout());
        jPanelTop.add(jTextFieldPath, java.awt.BorderLayout.CENTER);

        jButtonSelectPath.setText("...");
        jButtonSelectPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectPathActionPerformed(evt);
            }
        });
        jPanelTop.add(jButtonSelectPath, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanelTop, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });
        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectPathActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(File.listRoots()[0]);
        chooser.setDialogTitle("Choose Directory");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File sf = chooser.getSelectedFile();
            jTextFieldPath.setText(sf.getPath());
            fileSizeTree.setModel(new DefaultTreeModel(new DefaultMutableTreeNode(new PathSize(sf.getName(), 0))));
            FSTUtil fst = new FSTUtil(fileSizeTree, sf);
            this.setTitle("FileSizeTree (RUNNING)");
            fst.start();

        } else {
        }

    }//GEN-LAST:event_jButtonSelectPathActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable() {

            public void run() {
            }
        });

    }//GEN-LAST:event_formComponentResized

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized
        // TODO add your handling code here:
                Dimension size = jPanel1.getSize();
                size.width = size.height;
                jPanel1.setPreferredSize(size);
        
    }//GEN-LAST:event_jPanel1ComponentResized

    private void fileSizeTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_fileSizeTreeValueChanged
        // TODO add your handling code here:
        dataset.clear();
        DefaultMutableTreeNode node = (DefaultMutableTreeNode) fileSizeTree.getSelectionPath().getLastPathComponent();

        for( int i = 0; i<node.getChildCount(); i++)
        {
            PathSize ps = (PathSize) ((DefaultMutableTreeNode) node.getChildAt(i)).getUserObject();
            dataset.setValue( ps.getName(), ps.getSize());
        }

        chart.fireChartChanged();
    }//GEN-LAST:event_fileSizeTreeValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FileSizeTree().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree fileSizeTree;
    private javax.swing.JButton jButtonSelectPath;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPaneForTree;
    private javax.swing.JTextField jTextFieldPath;
    // End of variables declaration//GEN-END:variables
}
